### ISSUE TITLE
Lack of validation on start date field crashes the server

### ISSUE THREAD

**Issue by tedks** [mzenzie/320MusicLessonPlanner#65]
Adding a student record (in the source release distributed as the beta -- I haven't reproduced this on trunk) without a value set for start date causes an application crash. Backtrace:

``````
DB LIST
SELECT * FROM SRecord WHERE SRecord.tid=8
200 OK ========= 3
GET /api/studentRecord 304 3.834 ms - -
CTRLLER
{ firstName: 'test',
  lastName: 'test',
  instrument: 'testulute',
  email: 'test@test.com',
  phone: '555-555-5555',
  address: '1212 fake street',
  numberOfLessons: '10',
  lessonTime: '2015-04-09T16:00:00.318Z',
  lessonLength: '45 minutes',
  generalNotes: 'This is where notes on student progress should be placed. <b>Hopefully</b> formatting will work.' }
TID FOR INSERTION ======================== 8
CREATE
DB SAVE
{ firstName: 'test',
  lastName: 'test',
  instrument: 'testulute',
  email: 'test@test.com',
  phone: '555-555-5555',
  address: '1212 fake street',
  lessonTime: '2015-04-09T16:00:00.318Z',
  numberOfLessons: '10',
  lessonLength: '45 minutes',
  sid: null,
  lessonNotes: [],
  generalNotes: 'This is where notes on student progress should be placed. <b>Hopefully</b> formatting will work.',
  lessonSchedules: [] }
INSERT INTO SRecord (tid, firstName, lastName, email, address, phone, birthday, instrument, generalNotes) VALUES(8, 'test', 'test', 'test@test.com', '1212 fake street', '555-555-5555', '', 'testulute', 'This is where notes on student progress should be placed. <b>Hopefully</b> formatting will work.')
TID+======8
DB LIST
SELECT * FROM SRecord WHERE SRecord.tid=8
SELECT * FROM SRecord WHERE firstName='test' AND lastName='test' AND email='test@test.com' AND address='1212 fake street' AND phone='555-555-5555' AND birthday='' AND instrument = 'testulute'
== STUDENT RECORD SAVED! ==
{ firstName: 'test',
  lastName: 'test',
  instrument: 'testulute',
  email: 'test@test.com',
  phone: '555-555-5555',
  address: '1212 fake street',
  lessonTime: '2015-04-09T16:00:00.318Z',
  numberOfLessons: '10',
  lessonLength: '45 minutes',
  sid: 36,
  lessonNotes: [],
  generalNotes: 'This is where notes on student progress should be placed. <b>Hopefully</b> formatting will work.',
  lessonSchedules: [] }
SERIALIZD
{ date: Invalid Date,
  lessonTime: '2015-04-09T16:00:00.318Z',
  lessonLength: '45 minutes',
  numberOfLessons: '10' }

/home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/server/model/lesson-schedule.js:168
                    scheduleData.date.toISOString(),
                                      ^
RangeError: Invalid time value
    at Date.toISOString (native)
    at Database.<anonymous> (/home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/server/model/lesson-schedule.js:168:39)
    at Function.module.exports.generateDates (/home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/server/model/lesson-schedule.js:158:8)
    at /home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/server/model/student-record.js:328:28
    at Statement.<anonymous> (/home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/server/model/student-record.js:131:11)
    at Statement.replacement (/home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.replacement (/home/ted/Documents/School/320-software-eng/04-beta/mlp/320MusicLessonPlanner-0.2/node_modules/sqlite3/lib/trace.js:20:31)```

It's pretty bad that this is stored in the database, because it could lead to another crash bug later if the same formatting call is made on the invalid object.
``````

**Comment by nsimsiri** [comment]
Thank you for the post Ted. We are still working on the validations and the plan for now is to validate all post requests in the server-side controllers. If the validation is off, then we'll return a 400 with an error object. Hopefully along with good tests, we will reduce the chance of crashing the server.

**Comment by jesshmusic** [comment]
Fixed.
Not possible to have no value for starting date anymore.
